name: Deploy
on:
  workflow_run:
    workflows: Package
    branches: master
    types: completed

jobs:
  deploy:
    if: github.repository == 'keyteki/keyteki' && ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
        - name: Pull latest lobby image
          run: docker pull cryogen/keyteki-lobby
        - name: Stop and remove lobby image
          run: docker stop ${{ env.LOBBY_CONTAINER_NAME }} && docker rm ${{ env.LOBBY_CONTAINER_NAME }}
        - name: Run new lobby image
          run: docker run  docker run -d -p ${{ env.LOBBY_PORT }}:80 --network ${{ env.NETWORK_NAME }} -v ${{ env.AVATAR_PATH }}:/usr/src/app/public/img/avatar -v ${{ env.LOBBY_LOG_PATH }}:/usr/src/app/server/logs --name ${{ env.LOBBY_CONTAINER_NAME }} --env NODE_CONFIG='{"env":"production","sentryDsn":"${{ secrets.SENTRY_DSN }}","captchaKey":"${{ secrets.CAPTHCA_KEY }}","minLobbyChatTime":3600,"dbUser":"${{ secrets.DB_USER }}","dbHost":"host.docker.internal","dbDatabase":"${{ secrets.DB_NAME }}","dbPassword":"${{ secrets.DB_PASSWORD }}","dbPort":${{ secrets.DB_PORT }},"redisUrl":"${{ secrets.REDIS_URL }}","secret":"${{ secrets.SECRET }}","lobby":{"port":80,"emailKey":"${{ secrets.EMAIL_KEY }}","hmacSecret":"${{ secrets.HMAC }}","requireActivation":false,"lowerDeckThreshold":5,"middleDeckThreshold":20,"upperDeckThreshold":50}}' cryogen/keyteki-lobby
